### ISSUE TITLE
Dislocator has problems with IQEnergySink's NBT saving.

### ISSUE THREAD

**Issue by sammko** [HeisenBugDev/QuantumCraft#54]
Crash.

java.lang.NullPointerException
at mods.quantumcraft.machine.abstractmachines.TileEnergySink.writeToNBT(TileEnergySink.java:72)
at mods.quantumcraft.machine.TileQEInjector.writeToNBT(TileQEInjector.java:226)

**Comment by sammko** [comment]
oh, and it makes your world unusable.
