### ISSUE TITLE
I.O.N Forge

### ISSUE THREAD

**Issue by sammko** [HeisenBugDev/QuantumCraft#67]
A furnace that runs on Quantum Energy. Should be fast, upgradable and maybe be able to process 2 items at the same time.

**Comment by hunterboerner** [comment]
Super epic version of the induction furnace! :+1: :cake: :cool:

**Comment by hunterboerner** [comment]
I moved it to milestone 0.5 so that we can give people more than just power converters and a few tools.

**Comment by hunterboerner** [comment]
Just logging current errors

```
2013-11-01 09:57:18 [INFO] [STDOUT] [QuantumEnergyNet] Changed link detected.
2013-11-01 09:57:18 [INFO] [STDOUT] REPLACING SOURCE LIST
2013-11-01 09:57:18 [INFO] [STDOUT] REPLACING SOURCE LIST
2013-11-01 09:57:18 [INFO] [STDOUT] [QuantumEnergyNet] Changed link detected.
2013-11-01 09:57:18 [INFO] [STDOUT] REPLACING SOURCE LIST
2013-11-01 09:57:18 [INFO] [STDOUT] REPLACING SOURCE LIST
2013-11-01 09:57:18 [INFO] [STDERR] net.minecraft.util.ReportedException: Exception ticking world
2013-11-01 09:57:18 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:663)
2013-11-01 09:57:18 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:587)
2013-11-01 09:57:18 [INFO] [STDERR]     at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:129)
2013-11-01 09:57:18 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
2013-11-01 09:57:18 [INFO] [STDERR]     at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
2013-11-01 09:57:18 [INFO] [STDERR] Caused by: java.lang.RuntimeException: class quantumcraft.tile.TileIONForge is missing a mapping! This is a bug!
2013-11-01 09:57:18 [INFO] [STDERR]     at net.minecraft.tileentity.TileEntity.writeToNBT(TileEntity.java:108)
2013-11-01 09:57:18 [INFO] [STDERR]     at quantumcraft.tile.abstracttiles.TileMachineBase.writeToNBT(TileMachineBase.java:51)
2013-11-01 09:57:18 [INFO] [STDERR]     at quantumcraft.tile.abstracttiles.TileEnergySink.writeToNBT(TileEnergySink.java:88)
2013-11-01 09:57:18 [INFO] [STDERR]     at quantumcraft.tile.abstracttiles.TileMachineBase.getDescriptionPacket(TileMachineBase.java:30)
2013-11-01 09:57:18 [INFO] [STDERR]     at net.minecraft.server.management.PlayerInstance.sendTileToAllPlayersWatchingChunk(PlayerInstance.java:226)
2013-11-01 09:57:18 [INFO] [STDERR]     at net.minecraft.server.management.PlayerInstance.sendChunkUpdate(PlayerInstance.java:168)
2013-11-01 09:57:18 [INFO] [STDERR]     at net.minecraft.server.management.PlayerManager.updatePlayerInstances(PlayerManager.java:90)
2013-11-01 09:57:18 [INFO] [STDERR]     at net.minecraft.world.WorldServer.tick(WorldServer.java:203)
2013-11-01 09:57:18 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:657)
2013-11-01 09:57:18 [INFO] [STDERR]     ... 4 more
2013-11-01 09:57:18 [SEVERE] [Minecraft-Server] Encountered an unexpected exception ReportedException
net.minecraft.util.ReportedException: Exception ticking world
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:663)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:587)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:129)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.RuntimeException: class quantumcraft.tile.TileIONForge is missing a mapping! This is a bug!
    at net.minecraft.tileentity.TileEntity.writeToNBT(TileEntity.java:108)
    at quantumcraft.tile.abstracttiles.TileMachineBase.writeToNBT(TileMachineBase.java:51)
    at quantumcraft.tile.abstracttiles.TileEnergySink.writeToNBT(TileEnergySink.java:88)
    at quantumcraft.tile.abstracttiles.TileMachineBase.getDescriptionPacket(TileMachineBase.java:30)
    at net.minecraft.server.management.PlayerInstance.sendTileToAllPlayersWatchingChunk(PlayerInstance.java:226)
    at net.minecraft.server.management.PlayerInstance.sendChunkUpdate(PlayerInstance.java:168)
    at net.minecraft.server.management.PlayerManager.updatePlayerInstances(PlayerManager.java:90)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:203)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:657)
    ... 4 more
2013-11-01 09:57:18 [SEVERE] [Minecraft-Server] This crash report has been saved to: /Users/theron/Desktop/QC2/mcp/forge/mcp/jars/./crash-reports/crash-2013-11-01_09.57.18-server.txt
2013-11-01 09:57:18 [INFO] [Minecraft-Server] Stopping server
2013-11-01 09:57:18 [INFO] [Minecraft-Server] Saving players
2013-11-01 09:57:18 [INFO] [Minecraft-Server] hunterboerner left the game
2013-11-01 09:57:18 [INFO] [Minecraft-Server] Saving worlds
2013-11-01 09:57:18 [INFO] [Minecraft-Server] Saving chunks for level 'Copy of New World'/Overworld
2013-11-01 09:57:18 [SEVERE] [ForgeModLoader] A TileEntity type quantumcraft.tile.TileIONForge has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class quantumcraft.tile.TileIONForge is missing a mapping! This is a bug!
    at net.minecraft.tileentity.TileEntity.writeToNBT(TileEntity.java:108)
    at quantumcraft.tile.abstracttiles.TileMachineBase.writeToNBT(TileMachineBase.java:51)
    at quantumcraft.tile.abstracttiles.TileEnergySink.writeToNBT(TileEnergySink.java:88)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.writeChunkToNBT(AnvilChunkLoader.java:317)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.saveChunk(AnvilChunkLoader.java:127)
    at net.minecraft.world.gen.ChunkProviderServer.safeSaveChunk(ChunkProviderServer.java:232)
    at net.minecraft.world.gen.ChunkProviderServer.saveChunks(ChunkProviderServer.java:284)
    at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:901)
    at net.minecraft.server.MinecraftServer.saveAllWorlds(MinecraftServer.java:360)
    at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:393)
    at net.minecraft.server.integrated.IntegratedServer.stopServer(IntegratedServer.java:242)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:537)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
2013-11-01 09:57:18 [SEVERE] [ForgeModLoader] A TileEntity type quantumcraft.tile.TileIONForge has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException
    at quantumcraft.tile.abstracttiles.TileEnergySink.writeToNBT(TileEnergySink.java:87)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.writeChunkToNBT(AnvilChunkLoader.java:317)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.saveChunk(AnvilChunkLoader.java:127)
    at net.minecraft.world.gen.ChunkProviderServer.safeSaveChunk(ChunkProviderServer.java:232)
    at net.minecraft.world.gen.ChunkProviderServer.saveChunks(ChunkProviderServer.java:284)
    at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:901)
    at net.minecraft.server.MinecraftServer.saveAllWorlds(MinecraftServer.java:360)
    at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:393)
    at net.minecraft.server.integrated.IntegratedServer.stopServer(IntegratedServer.java:242)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:537)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
2013-11-01 09:57:18 [INFO] [Minecraft-Server] Saving chunks for level 'Copy of New World'/Nether
2013-11-01 09:57:18 [INFO] [Minecraft-Server] Saving chunks for level 'Copy of New World'/The End
2013-11-01 09:57:18 [INFO] [ForgeModLoader] Unloading dimension 0
2013-11-01 09:57:18 [INFO] [ForgeModLoader] Unloading dimension -1
2013-11-01 09:57:18 [INFO] [ForgeModLoader] Unloading dimension 1
2013-11-01 09:57:18 [INFO] [ForgeModLoader] The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
2013-11-01 09:57:19 [INFO] [STDOUT] ---- Minecraft Crash Report ----
2013-11-01 09:57:19 [INFO] [STDOUT] // Uh... Did I do that?
2013-11-01 09:57:19 [INFO] [STDOUT] 
2013-11-01 09:57:19 [INFO] [STDOUT] Time: 11/1/13 9:57 AM
2013-11-01 09:57:19 [INFO] [STDOUT] Description: Exception ticking world
2013-11-01 09:57:19 [INFO] [STDOUT] 
2013-11-01 09:57:19 [INFO] [STDOUT] java.lang.RuntimeException: class quantumcraft.tile.TileIONForge is missing a mapping! This is a bug!
2013-11-01 09:57:19 [INFO] [STDOUT]     at net.minecraft.tileentity.TileEntity.writeToNBT(TileEntity.java:108)
2013-11-01 09:57:19 [INFO] [STDOUT]     at quantumcraft.tile.abstracttiles.TileMachineBase.writeToNBT(TileMachineBase.java:51)
2013-11-01 09:57:19 [INFO] [STDOUT]     at quantumcraft.tile.abstracttiles.TileEnergySink.writeToNBT(TileEnergySink.java:88)
2013-11-01 09:57:19 [INFO] [STDOUT]     at quantumcraft.tile.abstracttiles.TileMachineBase.getDescriptionPacket(TileMachineBase.java:30)
2013-11-01 09:57:19 [INFO] [STDOUT]     at net.minecraft.server.management.PlayerInstance.sendTileToAllPlayersWatchingChunk(PlayerInstance.java:226)
2013-11-01 09:57:19 [INFO] [STDOUT]     at net.minecraft.server.management.PlayerInstance.sendChunkUpdate(PlayerInstance.java:168)
2013-11-01 09:57:19 [INFO] [STDOUT]     at net.minecraft.server.management.PlayerManager.updatePlayerInstances(PlayerManager.java:90)
2013-11-01 09:57:19 [INFO] [STDOUT]     at net.minecraft.world.WorldServer.tick(WorldServer.java:203)
2013-11-01 09:57:19 [INFO] [STDOUT]     at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:657)
2013-11-01 09:57:19 [INFO] [STDOUT]     at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:587)
2013-11-01 09:57:19 [INFO] [STDOUT]     at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:129)
2013-11-01 09:57:19 [INFO] [STDOUT]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
2013-11-01 09:57:19 [INFO] [STDOUT]     at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
2013-11-01 09:57:19 [INFO] [STDOUT] 
2013-11-01 09:57:19 [INFO] [STDOUT] 
2013-11-01 09:57:19 [INFO] [STDOUT] A detailed walkthrough of the error, its code path and all known details is as follows:
2013-11-01 09:57:19 [INFO] [STDOUT] ---------------------------------------------------------------------------------------
2013-11-01 09:57:19 [INFO] [STDOUT] 
2013-11-01 09:57:19 [INFO] [STDOUT] -- Head --
2013-11-01 09:57:19 [INFO] [STDOUT] Stacktrace:
2013-11-01 09:57:19 [INFO] [STDOUT]     at net.minecraft.tileentity.TileEntity.writeToNBT(TileEntity.java:108)
2013-11-01 09:57:19 [INFO] [STDOUT]     at quantumcraft.tile.abstracttiles.TileMachineBase.writeToNBT(TileMachineBase.java:51)
2013-11-01 09:57:19 [INFO] [STDOUT]     at quantumcraft.tile.abstracttiles.TileEnergySink.writeToNBT(TileEnergySink.java:88)
2013-11-01 09:57:19 [INFO] [STDOUT]     at quantumcraft.tile.abstracttiles.TileMachineBase.getDescriptionPacket(TileMachineBase.java:30)
2013-11-01 09:57:19 [INFO] [STDOUT]     at net.minecraft.server.management.PlayerInstance.sendTileToAllPlayersWatchingChunk(PlayerInstance.java:226)
2013-11-01 09:57:19 [INFO] [STDOUT]     at net.minecraft.server.management.PlayerInstance.sendChunkUpdate(PlayerInstance.java:168)
2013-11-01 09:57:19 [INFO] [STDOUT]     at net.minecraft.server.management.PlayerManager.updatePlayerInstances(PlayerManager.java:90)
2013-11-01 09:57:19 [INFO] [STDOUT]     at net.minecraft.world.WorldServer.tick(WorldServer.java:203)
2013-11-01 09:57:19 [INFO] [STDOUT] 
2013-11-01 09:57:19 [INFO] [STDOUT] -- Affected level --
2013-11-01 09:57:19 [INFO] [STDOUT] Details:
2013-11-01 09:57:19 [INFO] [STDOUT]     Level name: Copy of New World
2013-11-01 09:57:19 [INFO] [STDOUT]     All players: 1 total; [EntityPlayerMP['hunterboerner'/309, l='Copy of New World', x=198.22, y=64.00, z=287.98]]
2013-11-01 09:57:19 [INFO] [STDOUT]     Chunk stats: ServerChunkCache: 664 Drop: 0
2013-11-01 09:57:19 [INFO] [STDOUT]     Level seed: -7953702996799877046
2013-11-01 09:57:19 [INFO] [STDOUT]     Level generator: ID 00 - default, ver 1. Features enabled: true
2013-11-01 09:57:19 [INFO] [STDOUT]     Level generator options: 
2013-11-01 09:57:19 [INFO] [STDOUT]     Level spawn location: World: (236,64,252), Chunk: (at 12,4,12 in 14,15; contains blocks 224,0,240 to 239,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
2013-11-01 09:57:19 [INFO] [STDOUT]     Level time: 10108 game time, 10108 day time
2013-11-01 09:57:19 [INFO] [STDOUT]     Level dimension: 0
2013-11-01 09:57:19 [INFO] [STDOUT]     Level storage version: 0x04ABD - Anvil
2013-11-01 09:57:19 [INFO] [STDOUT]     Level weather: Rain time: 38001 (now: false), thunder time: 63509 (now: false)
2013-11-01 09:57:19 [INFO] [STDOUT]     Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
2013-11-01 09:57:19 [INFO] [STDOUT] Stacktrace:
2013-11-01 09:57:19 [INFO] [STDOUT]     at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:657)
2013-11-01 09:57:19 [INFO] [STDOUT]     at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:587)
2013-11-01 09:57:19 [INFO] [STDOUT]     at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:129)
2013-11-01 09:57:19 [INFO] [STDOUT]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
2013-11-01 09:57:19 [INFO] [STDOUT]     at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
2013-11-01 09:57:19 [INFO] [STDOUT] 
2013-11-01 09:57:19 [INFO] [STDOUT] -- System Details --
2013-11-01 09:57:19 [INFO] [STDOUT] Details:
2013-11-01 09:57:19 [INFO] [STDOUT]     Minecraft Version: 1.6.4
2013-11-01 09:57:19 [INFO] [STDOUT]     Operating System: Mac OS X (x86_64) version 10.8.4
2013-11-01 09:57:19 [INFO] [STDOUT]     Java Version: 1.7.0_25, Oracle Corporation
2013-11-01 09:57:19 [INFO] [STDOUT]     Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
2013-11-01 09:57:19 [INFO] [STDOUT]     Memory: 412651992 bytes (393 MB) / 902889472 bytes (861 MB) up to 1864171520 bytes (1777 MB)
2013-11-01 09:57:19 [INFO] [STDOUT]     JVM Flags: 3 total; -Xms512m -Xmx2000m -XX:MaxPermSize=128m
2013-11-01 09:57:19 [INFO] [STDOUT]     AABB Pool Size: 3856 (215936 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
2013-11-01 09:57:19 [INFO] [STDOUT]     Suspicious classes: FML and Forge are installed
2013-11-01 09:57:19 [INFO] [STDOUT]     IntCache: cache: 0, tcache: 0, allocated: 2, tallocated: 64
2013-11-01 09:57:19 [INFO] [STDOUT]     FML: MCP v8.11 FML v6.4.6.884 Minecraft Forge 9.11.0.884 10 mods loaded, 10 mods active
2013-11-01 09:57:19 [INFO] [STDOUT]     mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2013-11-01 09:57:19 [INFO] [STDOUT]     FML{6.4.6.884} [Forge Mod Loader] (mcp) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2013-11-01 09:57:19 [INFO] [STDOUT]     Forge{9.11.0.884} [Minecraft Forge] (mcp) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2013-11-01 09:57:19 [INFO] [STDOUT]     BuildCraft|Core{@VERSION@} [BuildCraft] (mods.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2013-11-01 09:57:19 [INFO] [STDOUT]     BuildCraft|Transport{@VERSION@} [Buildcraft Transport] (mods.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2013-11-01 09:57:19 [INFO] [STDOUT]     BuildCraft|Silicon{@VERSION@} [BuildCraft Silicon] (mods.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2013-11-01 09:57:19 [INFO] [STDOUT]     QuantumCraft{@VERSION@} [QuantumCraft] (mods.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2013-11-01 09:57:19 [INFO] [STDOUT]     BuildCraft|Builders{@VERSION@} [BuildCraft Builders] (mods.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2013-11-01 09:57:19 [INFO] [STDOUT]     BuildCraft|Energy{@VERSION@} [BuildCraft Energy] (mods.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2013-11-01 09:57:19 [INFO] [STDOUT]     BuildCraft|Factory{@VERSION@} [BuildCraft Factory] (mods.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
2013-11-01 09:57:19 [INFO] [STDOUT]     Profiler Position: N/A (disabled)
2013-11-01 09:57:19 [INFO] [STDOUT]     Vec3 Pool Size: 1708 (95648 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
2013-11-01 09:57:19 [INFO] [STDOUT]     Player Count: 1 / 8; [EntityPlayerMP['hunterboerner'/309, l='Copy of New World', x=198.22, y=64.00, z=287.98]]
2013-11-01 09:57:19 [INFO] [STDOUT]     Type: Integrated Server (map_client.txt)
2013-11-01 09:57:19 [INFO] [STDOUT]     Is Modded: Definitely; Client brand changed to 'fml,forge'
2013-11-01 09:57:19 [INFO] [STDOUT] #@!@# Game crashed! Crash report saved to: #@!@# /Users/theron/Desktop/QC2/mcp/forge/mcp/jars/./crash-reports/crash-2013-11-01_09.57.18-server.txt
AL lib: (EE) alc_cleanup: 1 device not closed
```

**Comment by hunterboerner** [comment]
that error fixed, just had to register the TE
